### ISSUE TITLE
Don't know how install the app

### ISSUE THREAD

**Issue by Lynokz** [Shishkebaboo/VodRecovery#10]
Hello, English is not my native language sorry, I'm desperately trying to install the application, I downloaded the latest version available and it's the first time I've used the site so I'm a bit lost, is it possible to have a quick explanation? Thank you very much for your work !

**Comment by Shishkebaboo** [comment]
@Lynokz Watch a couple youtube videos on github,  installing python, python modules and ffmpeg that's the best advice I can offer.

I do not provide step by step instructions because the items I noted above are very basic and already have hundred's if not thousands of video tutorials online via youtube.
