### ISSUE TITLE
Investigate cloudscraper github repository and use it to bypass cloudfare anti bot protection

### ISSUE THREAD

**Issue by Shishkebaboo** [Shishkebaboo/VodRecovery#20]

**Comment by Shishkebaboo** [comment]
Ive receieved confirmation from another person that this will not work for our purpose giving the following error:

![image](https://github.com/Shishkebaboo/VodRecovery/assets/118132878/401d154e-aa45-4086-8967-af83269ecc7d)

Closing this issue and going to try and look for another solution.

**Comment by knakamura8** [comment]
Had the same issue earlier.  Just saw this, however, which is a decent idea https://stackoverflow.com/questions/73923967/need-help-in-reaching-content-to-scrape-website-behind-cloudflare#comment130534044_73927740  Might have to resort to having users manually copy a browser response into input into the program.  A prompt perhaps that upon detecting the captcha in python, pauses, presents a hyperlink to the user, tells the user to then navigate to the page in a browser, pass the captcha, then copy the resulting token information from the browser into a prompt in the python program.

**Comment by knakamura8** [comment]
So, basically, once a user navigates to the page, they receive the `__cf_bm` token.  The python program and pause and wait for the user to copy this token into the python program, where it is then set as the header.  Yes, it requires the user to manually retrieve the token, but the several seconds of time isn't so bad, I don't think.  And this can be done without necessitating the use of the cloudscraper library at all, because it is just a header that needs to be programmatically added into the session request.
