### ISSUE TITLE
Is it Slower?

### ISSUE THREAD

**Issue by titusgroen** [Shishkebaboo/VodRecovery#33]
Does this seem.. slower in discovering if there even is a vod? Is this due to a change by Twitch?

**Comment by Shishkebaboo** [comment]
@titusgroen Yes, It would be a little bit slower due to having to finding available qualities.

**Comment by Shishkebaboo** [comment]
Its a trade off.... a bit slower in speed for functionality that was requested for repeatedly.

**Comment by titusgroen** [comment]
It doesn't seem just a little bit slower. It seems significantly slower to even just finding a VOD from the link than before. Maybe I'm doing something wrong? How long does it take for you?

**Comment by Shishkebaboo** [comment]
@titusgroen It takes me less then 5 seconds to use any of the functions other then downloading of which takes much longer as is probably expected. The script relies on a lot of things out of my control such as the websites it scrapes, user hardware, user connection status, user memory usage and so on. 

The only thing I could do to possibly make a difference is to add a timeout parameter which would raise an exception if the request did not respond within 5-10 seconds. However doing this would make it so anybody not getting a response back would instead of it taking forever the script would just error then return the main menu.

**Comment by Shishkebaboo** [comment]
@titusgroen Ive had people already doing absurdly hardware intensive tasks (90%+ memory usage) while using my script asking why its slow...  there is really not much I can do.

**Comment by titusgroen** [comment]
'm using either sullygnome or Twitchtracker links with 32gb RAM and only
using 30%. Are there best practices or anything else I can do to speed it
up for when I run it?
