### ISSUE TITLE
Changing download location

### ISSUE THREAD

**Issue by MickeyM007** [Shishkebaboo/VodRecovery#5]
Hello, Does anyone know how to change the download location? I really want to download the segments and the vod to a different drive and (sub) dir. But whatever I do in de config file, it download to the default location in documents.  I'm new at this, sorry! Thanks!!

**Comment by DirtyGodzilla** [comment]
There are two directories that you can change in the config file ("default" and "download"). Have you tried editing them both? Are you using the proper path to the directory?

I've had no trouble editing the config file and getting things to save where I want them to. Perhaps list the steps you're taking in the menu tree (ex: 1-Recover VOD; 1-Recover VOD; 2-Website VOD Recover; etc) so that someone can try to replicate your situation.

**Comment by MickeyM007** [comment]
Thanks for the reply!! What's the notation you use for the default and download locations in the config file? (ex D:\downloads\twitch)
The steps I take are: 1-1-2-'enter streamlink'-N-copy link'-6-1-'enter link'-N -> download starts

**Comment by DirtyGodzilla** [comment]
If you change the "default" directory that should be the one that gets saved to in your process (at least that's how it worked for me in following your steps). If you've changed that one already, it might be a file path issue. Maybe add a \ to the end of your example so that it's D:\downloads\twitch\?

**Comment by MickeyM007** [comment]
Aright, I think I figured it out. It's not a \ but / .
so: : `D:/downloads/twitch/`  (I use the code tags also haha)
Thanks for your help!!

**Comment by Shishkebaboo** [comment]
Ill have a look at this.. might need to change the way path's are defined.

**Comment by DirtyGodzilla** [comment]
> I use the code tags also haha

@MickeyM007 I made the suggestion to add a slash, and then _the slash I talked about wasn't showing up in my post_! Heh. And I couldn't figure out what escape character to use to get it to show. But then I realized, "use the 'code' tag, dummy".

Nice to see you got it sorted out.

**Comment by MickeyM007** [comment]
Is there a way to edit the config file so that the downloaded name is: `dd-mm-yyyy_<streamername>` ? 

Also when updating the py-script, what's the command to overwrite the files in the folder. If I clone now I get an error "dir. exists".
Or do I just remove everything before. I copied the new script in the dir. That didn't work. 

Sorry for all these questions!! I'm not good at script yet. I try to learn. Thanks!

**Comment by DirtyGodzilla** [comment]
> Is there a way to edit the config file so that the downloaded name is: `dd-mm-yyyy_<streamername>` ?

Are you perhaps looking for [something like this?](https://github.com/Shishkebaboo/VodRecovery/issues/4#issue-1608935498)

**Comment by MickeyM007** [comment]
Yes something like that, Because of the _"DATETIME VALUES"_ in the config file. 
The download output name now is: `<streamername>_<streamID>.mp4`
I thought it was a simple note that I had overlooked. 

Never mind! I'll stop asking questions haha.. I'm gonna teach myself first! Thanks @DirtyGodzilla !

**Comment by Shishkebaboo** [comment]
This is a duplicate issue of https://github.com/Shishkebaboo/VodRecovery/issues/4... Going to close this one.
